### ISSUE TITLE
SOAR in combination with?

### ISSUE THREAD

**Issue by naadali** [SoarGroup/Agents#3]

**Comment by garfieldnate** [comment]
Hi Ali, I did not understand your question. This repository contains agents to be used with the Soar Cognitive Architecture. We are not affiliated with any organization called "SOAR". I don't know if that's what you're asking.

**Comment by naadali** [comment]
Hello, I wanted to combine the SOAR architecture with other architectures
like LLM to form a new technology. what do you think about it?

**Comment by garfieldnate** [comment]
Sounds fun, go for it! You may be interested in this paper: https://arxiv.org/pdf/2306.06770.pdf.

I'm going to close this ticket. For general questions about Soar, please use one of the mailing lists:
https://soar.eecs.umich.edu/SoarSupport/MailingLists

**Comment by naadali** [comment]
Great, thank you so much. Please send me your personal email address.
